### ISSUE TITLE
Unable to start program 'Mono'

### ISSUE THREAD

**Issue by Erdroy** [xamarin/vs-mono-debugger-sample#2]
Hello
I've tried this sample, aaand 'got some problems.

At first, compiling, installing (the plugin) and then creating custom-flavor project is OK.
But when I'm trying to run the created program with simple "Hello, World" it says:
"**Unable to start program 'Mono'**", and this is caused by `DebugLauncher::LauchDebugTargets` - which is inside `Mono.Debugging.VisualStudio.dll`.

I'm using VS2015, Windows 10 (64 bit) with installed Mono x32 in "`C:\Program Files (x86)\Mono\`" which is also added to PATH variable ("`C:\Program Files (x86)\Mono\bin`").

**Comment by Erdroy** [comment]
Actually I've fixed this problem (installed **64bit Mono 4.8.1**), but got next one "Unable to start debugging." and something like (translated from Polish) "Couldn't find specified file".

**Comment by kzu** [comment]
@joj is out on vacation for the next few days, but he'll be able to look at it sometime next week.

Thanks!

**Comment by anniexclusive** [comment]
Is he back from vacation yet?? Because I am facing similar errors.

**Comment by joj** [comment]
That error means the actual mono debugger is not installed. In earlier versions of VS you had to had Xamarin to include that. In the latest releases (I think still in the preview channels) the mono debugger can be installed as an individual component. Sorry for the delay, I completely missed this conversation.

**Comment by anniexclusive** [comment]
Well I am using Visual Studio 2015, does it mean I have to install it independently, if yes please can I have the link to the download?
Actually my error is saying Invalid Pointer, what does it mean??
This is the log:
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 4.5.0.476-d15-2+1be4f0c
Xamarin.VisualStudio.Activation.AccountManager|Information|0|VS2015 Enterprise
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|No license found for iOS
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|Running license sync for iOS
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|Not logged in, using iOS VSEnterprise
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|No license found for Android
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|Running license sync for Android
Xamarin.VisualStudio.Activation.ActivationManager|Information|0|Not logged in, using Android VSEnterprise
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.VisualStudio.ProjectFixerRunner|Information|0|Solution loaded: 'test'
Xamarin.VisualStudio.ProjectFixerRunner|Information|0|running fixup on project 'C:\Users\AnnieXclusive\documents\visual studio 2015\Projects\test\test\test.Droid\test.Droid.csproj'
Xamarin.VisualStudio.Shell.UpdateService|Error|0|Error performing automatic update: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'software.xamarin.com'
   at System.Net.HttpWebRequest.GetResponse()
   at MonoDevelop.Core.Web.RequestHelper.GetResponse(CancellationToken token) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\ProxySupport\Nuget\RequestHelper.cs:line 115
   at Xamarin.VisualStudio.Proxy.VisualStudioWebRequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, CancellationToken token) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\ProxySupport\VisualStudioWebRequestHelper.cs:line 106
   at Xamarin.Components.Ide.Web.WebRequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, CancellationToken token)
   at Xamarin.VisualStudio.UpdateClient.<>c__DisplayClass1_0.<CheckUpdatesAsync>b__0() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Updater\UpdateClient.cs:line 74
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Shell.UpdateService.<CheckUpdatesAsync>d__32.MoveNext() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Shell\Updater\UpdateService.cs:line 198
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'software.xamarin.com'
   at System.Net.HttpWebRequest.GetResponse()
   at MonoDevelop.Core.Web.RequestHelper.GetResponse(CancellationToken token) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\ProxySupport\Nuget\RequestHelper.cs:line 115
   at Xamarin.VisualStudio.Proxy.VisualStudioWebRequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, CancellationToken token) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\ProxySupport\VisualStudioWebRequestHelper.cs:line 106
   at Xamarin.Components.Ide.Web.WebRequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, CancellationToken token)
   at Xamarin.VisualStudio.UpdateClient.<>c__DisplayClass1_0.<CheckUpdatesAsync>b__0() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Updater\UpdateClient.cs:line 74
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Shell.UpdateService.<CheckUpdatesAsync>d__32.MoveNext() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Shell\Updater\UpdateService.cs:line 198<---

Mono.Debugging.VisualStudio.DebugLauncher|Error|0|Controller.Launch ()
Xamarin.VisualStudio.ProgressReport|Error|0|System.Runtime.InteropServices.COMException (0x89710016): Invalid pointer

   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo)
   at Mono.Debugging.VisualStudio.MonoDebuggerLauncher.StartSession(StartInfo startInfo, SoftDebuggerSession session)
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.StartDebugger(IProgressReport progress, IAndroidProjectProperties properties, AndroidDevice device, String package, String activity, Project project) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 102
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.Execute(DebugCommand command, IProgressReport progress, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 56
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.Execute(TCommand command, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 65
Xamarin.VisualStudio.UnhandledExceptionsManager|Error|0|An unhandled error occurred. Details: Invalid pointer


System.Runtime.InteropServices.COMException (0x89710016): Invalid pointer

   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo)
   at Mono.Debugging.VisualStudio.MonoDebuggerLauncher.StartSession(StartInfo startInfo, SoftDebuggerSession session)
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.StartDebugger(IProgressReport progress, IAndroidProjectProperties properties, AndroidDevice device, String package, String activity, Project project) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 102
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.Execute(DebugCommand command, IProgressReport progress, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 56
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.Execute(TCommand command, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 85
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.<>c__DisplayClass1_0.<ExecuteAsync>b__0() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 53
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
Mono.Debugging.VisualStudio.DebugLauncher|Error|0|Controller.Launch ()
Xamarin.VisualStudio.ProgressReport|Error|0|System.Runtime.InteropServices.COMException (0x89710016): Invalid pointer

   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo)
   at Mono.Debugging.VisualStudio.MonoDebuggerLauncher.StartSession(StartInfo startInfo, SoftDebuggerSession session)
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.StartDebugger(IProgressReport progress, IAndroidProjectProperties properties, AndroidDevice device, String package, String activity, Project project) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 102
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.Execute(DebugCommand command, IProgressReport progress, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 56
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.Execute(TCommand command, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 65
Xamarin.VisualStudio.UnhandledExceptionsManager|Error|0|An unhandled error occurred. Details: Invalid pointer


System.Runtime.InteropServices.COMException (0x89710016): Invalid pointer

   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo)
   at Mono.Debugging.VisualStudio.MonoDebuggerLauncher.StartSession(StartInfo startInfo, SoftDebuggerSession session)
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.StartDebugger(IProgressReport progress, IAndroidProjectProperties properties, AndroidDevice device, String package, String activity, Project project) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 102
   at Xamarin.VisualStudio.Android.CommandHandlers.DebugCommandHandler.Execute(DebugCommand command, IProgressReport progress, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\CommandHandlers\DebugCommandHandler.cs:line 56
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.Execute(TCommand command, CancellationToken cancellationToken) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 85
   at Xamarin.VisualStudio.Commands.CommandHandlerBase`1.<>c__DisplayClass1_0.<ExecuteAsync>b__0() in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio\Commands\CommandHandlerBase.cs:line 53
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
Xamarin.VisualStudio.Android.MonoAndroidFlavoredProject|Error|0|The method or operation is not implemented.
System.NotImplementedException: The method or operation is not implemented.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.GetGuidProperty(UInt32 itemId, Int32 propId)
   at Xamarin.VisualStudio.Android.MonoAndroidFlavoredProject.GetGuidProperty(UInt32 itemId, Int32 propId) in C:\d\lanes\4699\1be4f0c9\source\xamarinvs\src\Core\VisualStudio.Android\ProjectSystem\MonoAndroidFlavoredProject.cs:line 335
Mono.Debugging.VisualStudio.DebugLauncher|Error|0|Controller.Launch ()
Xamarin.VisualStudio.ProgressReport|Error|0|System.Runtime.InteropServices.COMException (0x89710016): Invalid pointer

   at Microsoft.VisualStudio.Shell.Interop.IVsDebugger4.LaunchDebugTargets4(UInt32 DebugTargetCount, VsDebugTargetInfo4[] pDebugTargets, VsDebugTargetProcessInfo[] pLaunchResults)
   at Mono.Debugging.VisualStudio.DebugLauncher.StartDebugger(SoftDebuggerSession session, StartInfo startInfo)
   at Mono.Debugging.VisualStudio.MonoDe

Thank you.

**Comment by joj** [comment]
Oh. I never planned for 2015. Let me check internally if there's something we can publish. To test right now, you can install Xamarin in 2015 (just the VS part, no need for the SDKs) and it will work.

**Comment by joj** [comment]
It's actually in the nuget. If you look in src\packages\Mono.Debugging.VisualStudio.1.0.41-pre\tools you'll find a vsix (2 actually, ignore the "exp" one). That vsix is the debugger and needs to be installed for the sample to work.

**Comment by anniexclusive** [comment]
I cant find the path. How do I locate it please?

**Comment by joj** [comment]
That path is from the root of your repo, src being the first directory here: https://github.com/xamarin/vs-mono-debugger-sample/tree/master/src. This is assuming you have built and restored packages.

**Comment by anniexclusive** [comment]
I've ransacked my laptop, I cannot find the path and I don't know what you're talking about. Root of my what? Project file? Xamarin path? what?

**Comment by joj** [comment]
The root of your clone of this repo.

**Comment by anniexclusive** [comment]
Ok I understand you now. But I do not have that nugget in my packages, why is it missing?

**Comment by joj** [comment]
You shouldn't be able to compile without that. That's where Mono.Debugging.VisualStudio is coming from.

**Comment by anniexclusive** [comment]
Hmmmm

**Comment by anniexclusive** [comment]
Please someone else should help me!!!

**Comment by joj** [comment]
@anniexclusive are you at the moment able to build the sample? If you are, then finding that package should be fairly simple. Just do a detailed build, and look for the reference to Mono.Debugging.VisualStudio.dll. Wherever that file is, you'll find the vsix (just two directories up, and down into tools).

**Comment by anniexclusive** [comment]
![debug](https://user-images.githubusercontent.com/26500683/29936285-8a5c6496-8e79-11e7-981b-f6b1e4ee19a3.jpg)
well you can see that they are in the same directory.. both the vsix and mono.debugging.visualstudio.dll and it is not even .exe

**Comment by anniexclusive** [comment]
![debug2](https://user-images.githubusercontent.com/26500683/29936374-e1360c9a-8e79-11e7-9007-e63454320c05.jpg)
going up the two directories into the tools directory, there is nothing "vsix" there.

**Comment by joj** [comment]
Ok. You need to double-click on that to install it now.

**Comment by anniexclusive** [comment]
It doesn't allow to be installed. It opens as a text in Visual Studio.

[$RootKey$\InstalledProducts\MonoDebuggingPackage]
@="Mono Debugging for Visual Studio"
"PID"="Mono.Debugging.VisualStudio"
"ProductDetails"="Support for debugging Mono processes with Visual Studio."
[$RootKey$\Packages\{2315269f-53e7-4844-8213-8f954654b744}]
@="MonoDebuggingPackage"
"InprocServer32"="$WinDir$\SYSTEM32\MSCOREE.DLL"
"Class"="Mono.Debugging.VisualStudio.MonoDebuggingPackage"
"Assembly"="Mono.Debugging.VisualStudio.Vsix, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ec9700d15469a0df"
[$RootKey$\BindingPaths\{2315269F-53E7-4844-8213-8F954654B744}]
"$PackageFolder$"=""
[$RootKey$\AD7Metrics\PortSupplier\{fcee747d-e866-4221-bd96-99c30e4b67b9}]
"CLSID"="{a2c0cc70-c265-4807-901d-2e5a6378bf43}"
"Name"="Mono.Debugger"
[$RootKey$\CLSID\{a2c0cc70-c265-4807-901d-2e5a6378bf43}]
"InprocServer32"="$WinDir$\SYSTEM32\MSCOREE.DLL"
"Class"="Mono.Debugging.VisualStudio.PortSupplier"
"CodeBase"="$PackageFolder$\Mono.Debugging.VisualStudio.Vsix.dll"
"Assembly"="Mono.Debugging.VisualStudio.Vsix, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ec9700d15469a0df"
[$RootKey$\AD7Metrics\Engine\{9e1626ae-7db7-4138-ac41-641d55cf9a4a}]
"CLSID"="{c094c059-1786-49cd-8eb9-9c0ef6ca5454}"
"Name"="Mono.Debugging.VisualStudio.Engine"
"PortSupplier"="{a2c0cc70-c265-4807-901d-2e5a6378bf43}"
"CallstackBP"=dword:00000001
"AutoselectPriority"=dword:00000004
"Attach"=dword:00000000
"AddressBP"=dword:00000000
"Disassembly"=dword:00000000
"RemotingDebugging"=dword:00000000
"Exceptions"=dword:00000001
[$RootKey$\CLSID\{c094c059-1786-49cd-8eb9-9c0ef6ca5454}]
"InprocServer32"="$WinDir$\SYSTEM32\MSCOREE.DLL"
"Class"="Mono.Debugging.VisualStudio.Engine"
"CodeBase"="$PackageFolder$\Mono.Debugging.VisualStudio.Vsix.dll"
"Assembly"="Mono.Debugging.VisualStudio.Vsix, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ec9700d15469a0df"
[$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{5B7FF5E2-755B-3790-F69E-2AB27AEA3654}]
"name"="Mono.Debugging.VisualStudio.Vsix"
"publicKeyToken"="ec9700d15469a0df"
"culture"="neutral"
"version"="1.0.0.0"
"codeBase"="$PackageFolder$\Mono.Debugging.VisualStudio.Vsix.dll"
[$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{1B680C7A-F444-FB15-0480-D9026EF1991A}]
"name"="Mono.Debugging.VisualStudio"
"publicKeyToken"="ec9700d15469a0df"
"culture"="neutral"
"version"="1.0.0.0"
"codeBase"="$PackageFolder$\Mono.Debugging.VisualStudio.dll"

**Comment by joj** [comment]
You will need the Visual Studio SDK, which includes vsixinstaller.exe.

**Comment by joj** [comment]
Closing this as answered
